dashboard/urls.py
from django.urls import path
from . import views 

app_name = 'dashboard'
urlpatterns = [
    path('',views.index,name ='index'),
    path('login',views.login, name = 'login'),
]

djangoproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/',include("student.urls")),
    path('dashboard/', include("dashboard.urls")),
    path('teacher/', include("teacher.urls")),
    path('user/', include("user.urls")),
    path('report/', include("report.urls")),
    # path('eleve/',views.index),
    # path('eleve/ajouter',views.ajout),
]

report/urls.py
from django.urls import path
from . import views 

app_name = 'report'
urlpatterns = [
    path('',views.index,name = 'index'),
]

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('edit/<int:id>/', views.edit, name='edit'),  # Notez le slash final ici
    path('delete/<int:id>/', views.delete, name='delete'),  # Notez le slash final ici
]

teacher/urls.py
from django.urls import path
from . import views 

app_name = 'teacher'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('add/',views.add,name = 'add'),
    path('edit/<int:id>/', views.edit, name='edit'),  # Notez le slash final ici
    path('delete/<int:id>/', views.delete, name='delete'),
]

user/urls.py
from django.urls import path
from . import views 

app_name = 'user'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('add/',views.add, name = 'add'),
    path('edit<int:id>/',views.edit,name = 'edit'),
    
]

student/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=17)
    SEXE_CHOICES = [
        
        ('M', 'Male'),
        
        ('F', 'Female'),
    ]
    sex = models.CharField(max_length=1 , choices=SEXE_CHOICES)
    matricule = models.CharField(max_length=20, unique=True)
    birthday = models.DateField()
    STATUS_CHOICES = [
        ('6éme', '6éme'),
        ('5éme', '5éme'),
        ('4éme', '4éme'),
        ('3éme', '3eme'),
        ('2nde', '2nde'),
        ('1ére', '1ére'),
        ('Terminale', 'Terminale'),
        ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    phone = models.CharField(max_length=10)
    city = models.CharField(max_length=7)
    
    
    

student/forms.py
from  django import forms
from .models import Student
class EleveForms(forms.Form):
     nom = forms.CharField()
     prenom = forms.CharField()
     sexe = forms.CharField()
     matricule = forms.CharField()
     birthday = forms.DateField()
    
     statut = forms.CharField()
     phone = forms.CharField()
     ville = forms.CharField()
class StudentForms(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name','last_name','sex','birthday','status','matricule','phone','city']
        widgets = {'birthday': forms.DateInput(attrs={'type': 'date'}),
                  'phone':forms.NumberInput()}
        

    
    
    

    

student/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import StudentForms
from .models import  Student


# Create your views here.
def  index(request):
    list = Student.objects.all()
    context = {'elf':list}
    return render(request,"student/index.html",context)


def add(request):
    if request.method == "POST":
        formulai = StudentForms(request.POST)
        if formulai.is_valid():
            print("form is valid")
            formulai.save()
    formulai = StudentForms()
    context = {'formulai': formulai}
    return render(request,"student/add.html", context)


def edit(request,id):
    student_id = Student.objects.get(id=id)
    form = StudentForms(instance=student_id)
    if request.method == "POST":
        form = StudentForms(request.POST, instance=student_id)
        #formulai = StudentForms(request.POST)
        if form.is_valid():
            form.save()
        return redirect('student:index')
    formulai = StudentForms()
    context = {'formulai': form}
    return render(request,"student/edit.html",context)


def delete(request, id):
    student = Student.objects.get(id=id)
    student.delete()
    return redirect('student:index')

templates/student/add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}add new student{% endblock %}
{% block modifier %}
<div class="content">
      <div class="back-button" style="justify-content: flex-end">
        <a href="{% url "student:index" %}"><i class="fas fa-arrow-left"></i> Return</a>
      </div>
      <h2>add new student</h2>
      <form  method="post">
      {%  csrf_token %}

      <div class="form-container">
      {{formulai |crispy}}
        {% comment %} <h1>Ajouter un élève</h1>

        <div class="form-group">
          <label for="nom">Nom</label>
          <input type="text" id="nom" name="nom" />
        </div>

        <div class="form-group">
          <label for="prenom">Prénom</label>
          <input type="text" id="prenom" name="prenom" />
        </div>

        <div class="form-group gender">
          <label>Sexe</label>
          <div>
            <input type="radio" id="homme" name="sexe" value="homme" />
            <label for="homme">Homme</label>
          </div>
          <div>
            <input type="radio" id="femme" name="sexe" value="femme" />
            <label for="femme">Femme</label>
          </div>
        </div>

        <div class="form-group">
          <label for="matricule">Matricule</label>
          <input type="text" id="matricule" name="matricule" />
        </div>

        <div class="form-group">
          <label for="dateNaissance">Date de naissance</label>
          <input type="date" id="dateNaissance" name="dateNaissance" />
        </div>

        <div class="form-group">
          <label for="classe">Sélectionner une classe</label>
          <select id="classe" name="classe">
            <option value="6eme">6ème</option>
            <option value="5eme">5ème</option>
            <option value="4eme">4ème</option>
            <option value="3eme">3ème</option>
            <option value="2nde">2nde</option>
            <option value="1ere">1ère</option>
            <option value="terminale">Terminale</option>
          </select>
        </div>

        <div class="form-group">
          <label for="telephone">Téléphone</label>
          <input type="text" id="telephone" name="telephone" />
        </div>

        <div class="form-group">
          <label for="ville">Ville</label>
          <input type="text" id="ville" name="ville" />
        </div> {% endcomment %}

        <div class="form-actions">
          <button class="btn-cancel" onclick="confirmCancel()">cancel</button>
          <button type="submit" class="btn-save">save</button>
        </div>
      </div>
    </div>
  </form>
{% endblock %}
    

    
    

templates/student/edit.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}
{% block title %}edit new student{% endblock %} 
{%block modifier %}

<div class="content">
  <div class="back-button" style="justify-content: flex-end">
    <a href="{% url 'student:index' %}"
      ><i class="fas fa-arrow-left"></i> Return</a
    >
  </div>
  <h2>edit new student</h2>
  <form  method="post">
      {%  csrf_token %}

  <div class="form-container">
    {{formulai |crispy}}

    {% comment "" %}<h1>Mofidier un élève</h1>
    <div class="form-group">
      <label for="nom">Nom</label>
      <input type="text" id="nom" name="nom" />
    </div>

    <div class="form-group">
      <label for="prenom">Prénom</label>
      <input type="text" id="prenom" name="prenom" />
    </div>

    <div class="form-group gender">
      <label>Sexe</label>
      <div>
        <input type="radio" id="homme" name="sexe" value="homme" />
        <label for="homme">Homme</label>
      </div>
      <div>
        <input type="radio" id="femme" name="sexe" value="femme" />
        <label for="femme">Femme</label>
      </div>
    </div>

    <div class="form-group">
      <label for="matricule">Matricule</label>
      <input type="text" id="matricule" name="matricule" />
    </div>

    <div class="form-group">
      <label for="dateNaissance">Date de naissance</label>
      <input type="date" id="dateNaissance" name="dateNaissance" />
    </div>

    <div class="form-group">
      <label for="classe">Sélectionner une classe</label>
      <select id="classe" name="classe">
        <option value="6eme">6ème</option>
        <option value="5eme">5ème</option>
        <option value="4eme">4ème</option>
        <option value="3eme">3ème</option>
        <option value="2nde">2nde</option>
        <option value="1ere">1ère</option>
        <option value="terminale">Terminale</option>
      </select>
    </div>

    <div class="form-group">
      <label for="telephone">Téléphone</label>
      <input type="text" id="telephone" name="telephone" />
    </div>

    <div class="form-group">
      <label for="ville">Ville</label>
      <input type="text" id="ville" name="ville" />
    </div>
{% endcomment %}
    <div class="form-actions">
      <button class="btn-cancel" onclick="confirmCancel()">cancel</button>
      <button class="btn-save">save</button>
    </div>
  </div>
</div>
{% endblock %}

templates/student/index.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mon Etab - Tableau de bord</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <script
  src="https://code.jquery.com/jquery-3.7.1.js"
  integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
  crossorigin="anonymous"></script>
    {% comment %} <script src="{% static 'js/script.js'%}" defer> </script> {% endcomment %}

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />
    

  </head>
  <body>
    <div class="sidebar">
      <h2>Mon Etab</h2>
      <hr />
      <ul>
        <li>
          <a href="{% url "dashboard:index" %}"
            ><i class="fas fa-tachometer-alt"></i> dDa</a
          >
        </li>
        <li class="active">
          <a href="{% url "student:index" %}"><i class="fas fa-user-graduate"></i> student</a>
        </li>
        <li>
          <a href="{% url "teacher:index" %}"
            ><i class="fas fa-chalkboard-teacher"></i> teacher</a
          >
        </li>
        <li>
          <a href="{% url "user:index" %}"
            ><i class="fas fa-chalkboard-teacher"></i> user</a
          >
        </li>
        <li>
          <a href="{% url "report:index" %}"><i class="fas fa-chart-line"></i> report</a>
        </li>
      </ul>
      <hr style="margin-top: 270px" />
      <ul>
        <li>
          <a href="{% url "dashboard:login" %}"
            ><i class="fas fa-sign-out-alt"></i> sign out</a
          >
        </li>
      </ul>
    </div>
    <div class="content1">
      <div class="back-button">
        <h1 style="color: black"> student List </h1>
        <a href="{% url "student:add" %}"
          ><i class="fas fa-arrow-left"></i>New student</a
        >
      </div>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>last_name</th>
            <th>sex</th>
            <th>matricule</th>
            <th>birthday</th>
            <th>status</th>
            <th>phone</th>
            <th>city</th>
            <th>Actions</th>
          </tr>
        </thead>
  
        <tbody>
          {% for student in elf %}
          <tr>
            <td>{{  student.name }}</td>
            <td>{{  student.last_name }}</td>
            <td>{{  student.sex }}</td>
            <td>{{  student.matricule }}</td>
            <td>{{  student.birthday }}</td>
            <td>{{  student.status}}</td>
            <td>{{  student.phone }}</td>
            <td>{{  student.city }}</td>
            <td>
              <a style="background-color: rgba(255, 217, 0, 0.897)" href="{% url 'student:edit' student.id %}">
                         
                edit
            </a>
            <button style="background-color: rgba(255, 217, 0, 0.897)" class="delete-icon" data-id="{{ student.id }}">
    delete
</button>


            </td>
          </tr>
          
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="popup0" id="confirmationPopup">
      <div class="confirmation-container">
        <h2>Êtes-vous sûr de vouloir supprimer cet élève ?</h2>
        <form id="deleteForm" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn-confirm">comfirm</button>
    <button type="button" class="btn-cancel" onclick="closePopup()">cancel</button>
</form>
      </div>
    </div>

    
    <script>
      document.addEventListener("DOMContentLoaded", function () {
    const deleteIcons = document.querySelectorAll(".delete-icon");
    const popup = document.getElementById("confirmationPopup");
    const deleteForm = document.getElementById("deleteForm");

    deleteIcons.forEach(icon => {
        icon.addEventListener("click", function () {
            const id = this.getAttribute("data-id");
            deleteForm.action = `/student/delete/${id}/`;  // Ajout d'un slash final ici
            popup.style.display = "flex";
        });
    });
});

function closePopup() {
    document.getElementById("confirmationPopup").style.display = "none";
}

    </script>
    <script src="{% static 'js/script.js'%}" defer> </script>
  </body>
</html>