dashboard/urls.py
from django.urls import path
from . import views 

app_name = 'dashboard'
urlpatterns = [
    path('',views.index,name ='index'),
    path('login',views.login, name = 'login'),
]

djangoproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/',include("student.urls")),
    path('dashboard/', include("dashboard.urls")),
    path('teacher/', include("teacher.urls")),
    path('user/', include("user.urls")),
    path('report/', include("report.urls")),
    # path('eleve/',views.index),
    # path('eleve/ajouter',views.ajout),
]

report/urls.py
from django.urls import path
from . import views 

app_name = 'report'
urlpatterns = [
    path('',views.index,name = 'index'),
]

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('edit/<int:id>/', views.edit, name='edit'),  # Notez le slash final ici
    path('delete/<int:id>/', views.delete, name='delete'),  # Notez le slash final ici
]

teacher/urls.py
from django.urls import path
from . import views 

app_name = 'teacher'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('add/',views.add,name = 'add'),
    path('edit/<int:id>/', views.edit, name='edit'),  # Notez le slash final ici
    path('delete/<int:id>/', views.delete, name='delete'),
]

user/urls.py
from django.urls import path
from . import views 

app_name = 'user'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('add/',views.add, name = 'add'),
    path('edit<int:id>/',views.edit,name = 'edit'),
    
]

teacher/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    name = models.CharField(max_length=10)
    last_name = models.CharField(max_length=17)
    SEXE_CHOICES = [
        
        ('M', 'Male'),
        ('F', 'Female'),
    ]
    sex = models.CharField(max_length=1 , choices=SEXE_CHOICES)
    birthday = models.DateField(null = True)
    STATUS_CHOICES = [
        ('Math', 'Math'),
        ('Physique', 'Physique'),
        ('Eps', 'Eps'),
        ('Anglais', 'Anglais'),
        ('SVT', 'SVT'),
        ('Philosophie', 'Philosophie'),
        ('Français', 'Français'),
        ]
    course = models.CharField(max_length=15, choices=STATUS_CHOICES)
    phone = models.CharField(max_length=10)
    city = models.CharField(max_length=7)
    
    
    
    

teacher/forms.py
from  django import forms
from .models import Teacher
class TeacherForms(forms.Form):
    name = forms.CharField()
    last_name = forms.CharField()
   
    sex = forms.CharField()
    birthday = forms.DateField()
    
    course = forms.CharField()
    phone = forms.CharField()
    city = forms.CharField()
    
class TeacherForms(forms.ModelForm):
 class Meta:
        model = Teacher
        fields = ['name','last_name','sex','birthday','course','phone','city']
        
        widgets = {'birthday': forms.DateInput(attrs={'type': 'date'}),
                  'phone':forms.NumberInput()}
        
    
    
    


    

teacher/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import TeacherForms
from .models import Teacher
# Create your views here.
def  index(request): 
    list = Teacher.objects.all()
    context = {'rappe':list}
    return render(request,"teacher/index.html", context)


def add(request):
    if request.method == "POST":
        formulai = TeacherForms(request.POST)
        if formulai.is_valid():
            formulai.save()
    formulai = TeacherForms()
    context = {'formulai': formulai}
    return render(request,"teacher/add.html", context)


def edit(request, id):
    teacher_id = Teacher.objects.get(id=id)
    form = TeacherForms(instance=teacher_id)
    if request.method == "POST":
        form = TeacherForms(request.POST,instance=teacher_id)
        if form.is_valid():
            form.save()
            return redirect('teacher:index')
    
    context = {'formulai': form}
    return render(request,"teacher/edit.html",context)


def delete(request, id):
    teacher_id = Teacher.objects.get(id=id)
    teacher_id.delete()
    return redirect('teacher:index')

templates/teacher/add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}add new teacher{% endblock %}
{% block modifier %}
    <div class="content">
      <div class="back-button" style="justify-content: flex-end">
        <a href="{% url "teacher:index" %}"><i class="fas fa-arrow-left"></i> Return</a>
      </div>
      <h2>add new teacher</h2>
      <form  method="post">
        {%  csrf_token %}
      <div class="form-container">
        {{formulai |crispy}}
      {% comment "" %}
        <h1>Ajouter d'un professeur</h1>

        <div class="form-group">
          <label for="nom">Nom</label>
          <input type="text" id="nom" name="nom" />
        </div>

        <div class="form-group">
          <label for="prenom">Prénom</label>
          <input type="text" id="prenom" name="prenom" />
        </div>

        <div class="form-group gender">
          <label>Sexe</label>
          <div>
            <input type="radio" id="homme" name="sexe" value="homme" />
            <label for="homme">Homme</label>
          </div>
          <div>
            <input type="radio" id="femme" name="sexe" value="femme" />
            <label for="femme">Femme</label>
          </div>
        </div>

        <div class="form-group">
          <label for="dateNaissance">Date de naissance</label>
          <input type="date" id="dateNaissance" name="dateNaissance" />
        </div>

        <div class="form-group">
          <label for="classe">Sélectionner une matière</label>
          <select id="classe" name="classe">
            <option value="1">Math</option>
            <option value="2">physique</option>
            <option value="3">Eps</option>
            <option value="4">Anglais</option>
            <option value="5">SVT</option>
            <option value="6">philosophie</option>
            <option value="7">Français</option>
          </select>
        </div>

        <div class="form-group">
          <label for="telephone">Téléphone</label>
          <input type="text" id="telephone" name="telephone" />
        </div>

        <div class="form-group">
          <label for="ville">Ville</label>
          <input type="text" id="ville" name="ville" />
        </div>
{% endcomment %}
        <div class="form-actions">
          <button class="btn-cancel" onclick="confirmCancel()">cancel</button>
          <button class="btn-save">save</button>
        </div>
      </div>
    </div>
    {% endblock %}
    
    
  

templates/teacher/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}edit new teacher{% endblock %}
{% block modifier %}
     <div class="content">
      <div class="back-button" style="justify-content: flex-end">
        <a href="{% url "teacher:index" %}"><i class="fas fa-arrow-left"></i> Return</a>
      </div>
      <h2>edit new teacher</h2>
      <form  method="post">
        {%  csrf_token %}
      <div class="form-container">
        {{formulai |crispy}}
        {% comment "" %}<h1>Mofidier un professeur</h1>

        <div class="form-group">
          <label for="nom">Nom</label>
          <input type="text" id="nom" name="nom" />
        </div>

        <div class="form-group">
          <label for="prenom">Prénom</label>
          <input type="text" id="prenom" name="prenom" />
        </div>

        <div class="form-group gender">
          <label>Sexe</label>
          <div>
            <input type="radio" id="homme" name="sexe" value="homme" />
            <label for="homme">Homme</label>
          </div>
          <div>
            <input type="radio" id="femme" name="sexe" value="femme" />
            <label for="femme">Femme</label>
          </div>
        </div>

        <div class="form-group">
          <label for="dateNaissance">Date de naissance</label>
          <input type="date" id="dateNaissance" name="dateNaissance" />
        </div>

        <div class="form-group">
          <label for="classe">Sélectionner une matière</label>
          <select id="classe" name="classe">
            <option value="1">Math</option>
            <option value="2">Physique</option>
            <option value="3">Eps</option>
            <option value="4">Anglais</option>
            <option value="5">SVT</option>
            <option value="6">Philosophie</option>
            <option value="7">Français</option>
          </select>
        </div>

        <div class="form-group">
          <label for="telephone">Téléphone</label>
          <input type="text" id="telephone" name="telephone" />
        </div>

        <div class="form-group">
          <label for="ville">Ville</label>
          <input type="text" id="ville" name="ville" />
        </div>
      {% endcomment %}
        <div class="form-actions">
          <button class="btn-cancel" onclick="confirmCancel()">cancel</button>
          <button class="btn-save">save</button>
        </div>
      </div>
    </div>
{% endblock %}
    

   

templates/teacher/index.html
{%load static %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mon Etab - Tableau de bord</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />

    <script src={% static 'js/script.js'%} defer></script>
  </head>
  <body>
    <div class="sidebar">
      <h2>Mon Etab</h2>
      <hr />
      <ul>
        <li>
          <a href="{% url "dashboard:index" %}"
            ><i class="fas fa-tachometer-alt"></i> Tableau de bord</a
          >
        </li>
        <li class="active">
          <a href="{% url "student:index" %}"><i class="fas fa-user-graduate"></i> student</a>
        </li>
        <li>
          <a href="{% url "teacher:index" %}"
            ><i class="fas fa-chalkboard-teacher"></i> teacher</a
          >
        </li>
        <li>
          <a href="{% url "user:index" %}"
            ><i class="fas fa-chalkboard-teacher"></i> user</a
          >
        </li>
        <li>
          <a href="{% url "report:index" %}"><i class="fas fa-chart-line"></i> Report</a>
        </li>
      </ul>
      <hr style="margin-top: 270px" />
      <ul>
        <li>
          <a href="{% url "dashboard:login" %}"
            ><i class="fas fa-sign-out-alt"></i> sign out </a
          >
        </li>
      </ul>
    </div>
    <div class="content1">
      <div class="back-button">
        <h1 style="color: black">teacher List</h1>
        <a href="{% url "teacher:add" %}"
          ><i class="fas fa-arrow-left"></i>New teacher</a
        >
      </div>
      <table>
        <thead>
          <tr>
            <th>name</th>
            <th>last_name</th>
            <th>sex</th>
            <th>course</th>
            <th>phone</th>
            <th>city</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for teacher in rappe%}
          <tr>
            <td>{{ teacher.name}}</td>
            <td>{{teacher.last_name }}</td>
            <td>{{teacher.sex }}</td>
            <td>{{teacher.course}}</td>
            <td>{{teacher.phone}}</td>
            <td>{{teacher.city}}</td>
            
            <td>
              <a style="background-color: rgba(255, 217, 0, 0.897)" href="{% url 'teacher:edit' teacher.id %}">
                edit
              </a>
              <button  style="background-color: rgb(212, 21, 21)"  class="delete-icon" data-id="{{ teacher.id }}">
                delete
              </button>
            </td>
          </tr>
          {%endfor%}

        </tbody>
      </table>
    </div>

    <div class="popup0" id="confirmationPopup">
      <div class="confirmation-container">
        <h2>Êtes-vous sûr de vouloir supprimer ce teacher </h2>
        <form id="deleteForm" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn-confirm">comfirm</button>
    <button type="button" class="btn-cancel" onclick="closePopup()">cancel</button>
</form>
      </div>
    </div>

    <script>
      document.addEventListener("DOMContentLoaded", function () {
        const deleteIcons = document.querySelectorAll(".delete-icon");
        const popup = document.getElementById("confirmationPopup");
        const deleteForm = document.getElementById("deleteForm");

        deleteIcons.forEach((icon) => {
          icon.addEventListener("click", function () {
            const id = this.getAttribute("data-id");
            deleteForm.action = `/teacher/delete/${id}/`;
            popup.style.display = "flex";
          });
        });
      });

      function closePopup() {
        document.getElementById("confirmationPopup").style.display = "none";
      }
    </script>
    <script src= {% static 'js/script.js'%} defer></script>
  </body>
</html>