dashboard/urls.py
from django.urls import path
from . import views 

app_name = 'dashboard'
urlpatterns = [
    path('',views.index,name ='index'),
    path('login',views.login, name = 'login'),
]

djangoproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/',include("student.urls")),
    path('dashboard/', include("dashboard.urls")),
    path('teacher/', include("teacher.urls")),
    path('user/', include("user.urls")),
    path('report/', include("report.urls")),
    # path('eleve/',views.index),
    # path('eleve/ajouter',views.ajout),
]

report/urls.py
from django.urls import path
from . import views 

app_name = 'report'
urlpatterns = [
    path('',views.index,name = 'index'),
]

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('edit/<int:id>/', views.edit, name='edit'),  # Notez le slash final ici
    path('delete/<int:id>/', views.delete, name='delete'),  # Notez le slash final ici
]

teacher/urls.py
from django.urls import path
from . import views 

app_name = 'teacher'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('add/',views.add,name = 'add'),
    path('edit/<int:id>/', views.edit, name='edit'),  # Notez le slash final ici
    path('delete/<int:id>/', views.delete, name='delete'),
]

user/urls.py
from django.urls import path
from . import views 

app_name = 'user'
urlpatterns = [
    path('',views.index,name = 'index'),
    path('add/',views.add, name = 'add'),
    path('edit<int:id>/',views.edit,name = 'edit'),
    
]

user/models.py
from django.db import models
# Create your models here.
class User(models.Model):
    pseudo = models.CharField(max_length=15) 
    password= models.CharField(max_length=30) 
    create_at = models.DateField(auto_now_add=True)

user/forms.py
from  django import forms
from .models import User

class UserForms(forms.Form):
    pseudo = forms.CharField() 
    password = forms.CharField() 
    

class UserForms(forms.ModelForm):
    class Meta:
         model = User
         fields = ['pseudo','password',]
        
        

    

user/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import UserForms
from .models import User
from django.contrib.auth.models import User as  SuperUser

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from django.contrib import messages

# Create your views here.
def  index(request):
    list = User.objects.all()
    context = {'dork':list}
    return render(request,"user/index.html",context)

def add(request):
     if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        
        if not username or not password:
            return render(request, 'html/signin.html')
        
        user = User(username=username)
        user.save()
        user.set_password(user.password)
        user.save()
        login(request,user)
        return redirect("authApp:Home")
     
        if request.method == "POST":
        
            formulai = UserForms(request.POST)
        if  formulai.is_valid():
            formulai.save() 
            formulai = UserForms()
        context = {'formulai': formulai} 
        return render(request,"user/add.html",context)

def edit(request, id):
    user_id = User.objects.get(id=id)
    if request.method == "POST":
        form = UserForms(request.POST,instance=user_id)
        if form.is_valid():
           form.save()
           return redirect('user:index')
    form = UserForms(instance=user_id)
    context = {'formulai': form}
    return render(request,"user/edit.html",context)


#def delete(request,id):
    #user_id = Teacher.objects.get(id=id)
    #user_id.delete()
    #return redirect('user:index')

templates/user/add.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}add new user{% endblock %}
{% block modifier %}

    <div class="content">
      <div class="back-button" style="justify-content: flex-end">
        <a href="{% url "user:index" %}"><i class="fas fa-arrow-left"></i> Return</a>
      </div>
      <h2>add new user</h2>
      <form  method="post">
        {%  csrf_token %}
      <div class="form-container">
        {{formulai |crispy}}
        {% comment %} <h1>Ajouter un utilisateur</h1>

        <div class="form-group">
          <label for="nom">Pseudo</label>
          <input type="text" id="nom" name="nom" />
        </div>

        <div class="form-group">
          <label for="prenom">Mot de passe</label>
          <input type="text" id="prenom" name="prenom" />
        </div>

        <div class="form-group">
          <label for="matricule">Confirmez le mot de passe</label>
          <input type="text" id="matricule" name="matricule" />
        </div>
        {% endcomment %}
        <div class="form-actions">
          <button class="btn-cancel" onclick="confirmCancel()">cancel</button>
          <button class="btn-save">save</button>
        </div>
      </div>
    </div>
{% endblock %}
    

templates/user/edit.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}edit new user{% endblock %}
{% block modifier %}

    <div class="content">
      <div class="back-button" style="justify-content: flex-end">
        <a href="{% url "user:index" %}"><i class="fas fa-arrow-left"></i> Retour</a>
      </div>
      <h2>edit new user</h2>
      <form  method="post">
        {%  csrf_token %}
      <div class="form-container">

        {% comment %} <div class="form-group">
          <label for="nom">Pseudo</label>
          <input type="text" id="nom" name="nom" />
        </div>

        <div class="form-group">
          <label for="prenom">Mot de passe</label>
          <input type="text" id="prenom" name="prenom" />
        </div>

        <div class="form-group">
          <label for="matricule">Confirmez le mot de passe</label>
          <input type="text" id="matricule" name="matricule" />
        </div> {% endcomment %}
        {{formulai | crispy }}
        <div class="form-actions">
          <button class="btn-cancel" onclick="confirmCancel()">cancel</button>
          <button class="btn-save">save </button>
        </div>
      </div>
    </div>
{% endblock %}
       

templates/user/index.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mon Etab - Tableau de bord</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
    />
  
    <script src={% static 'js/script.js'%} defer> </script>
  </head>
  <body>
    <div class="sidebar">
      <h2>Mon Etab</h2>
    </hr >
      <ul>
        <li>
          <a href="{% url "dashboard:index" %}"
            ><i class="fas fa-tachometer-alt"></i> Tableau de bord</a
          >
        </li>
        <li class="active">
          <a href="{% url "student:index" %}"><i class="fas fa-user-graduate"></i> student</a>
        </li>
        <li>
          <a href="{% url "teacher:index" %}"
            ><i class="fas fa-chalkboard-teacher"></i> teacher</a
          >
        </li>
        <li>
          <a href="{% url "user:index" %}"
            ><i class="fas fa-chalkboard-teacher"></i> User</a
          >
        </li>
        <li>
          <a href="{% url "report:index" %}"><i class="fas fa-chart-line"></i> Report</a>
        </li>
      </ul>
      <hr style="margin-top: 270px" />
      <ul>
        <li>
          <a href="{% url "dashboard:login" %}"
            ><i class="fas fa-sign-out-alt"></i> sign out</a
          >
        </li>
      </ul>
    </div>
    <div class="content1">
      <div class="back-button">
        <h1 style="color: black"> user List</h1>
        <a href="{% url 'user:add' %}"
          ><i class="fas fa-arrow-left"></i>New user</a
        >
      </div>
      <table>
        <thead>
          <tr>
            <th>Pseudo</th>
            <th>Date de création</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for user in dork %}
            <tr>
              <td>{{ user.pseudo }}</td>
              <td>{{ user.create_at }}</td>
              <td>
                <a style="background-color: rgba(255, 217, 0, 0.897)" href="{% url "user:edit" user.id %}">
                  edit
                </a>

              </td>
            </tr>
            <tr>
            </tr>
          {% endfor%}
        </tbody>
      </table>
    </div>

    <div class="popup0" id="confirmationPopup">
      <div class="confirmation-container">
        <h2>Êtes-vous sûr de vouloir supprimer cet élève ?</h2>
        <form id="deleteForm" method="POST">
          <button type="submit" class="btn-confirm">Confirmer</button>
          <button type="button" class="btn-cancel" onclick="closePopup()">
            Annuler
          </button>
        </form>
      </div>
    </div>

    <script>
      document.addEventListener("DOMContentLoaded", function () {
        const deleteIcons = document.querySelectorAll(".delete-icon");
        const popup = document.getElementById("confirmationPopup");
        const deleteForm = document.getElementById("deleteForm");

        deleteIcons.forEach((icon) => {
          icon.addEventListener("click", function () {
            const id = this.getAttribute("data-id");
            deleteForm.action = `/admin/supprimer_client/${id}`;
            popup.style.display = "flex";
          });
        });
      });

      function closePopup() {
        document.getElementById("confirmationPopup").style.display = "none";
      }
    </script>
    {% comment %}
    <script src="{% static 'js/script.js'%}" />
    {% endcomment %}
    <script src="scripte.js"></script>
  </body>
</html>